name: Sabira Collection
favicon: null
layout_spectrum: 0.19317705370485783
typography_spectrum: 0.06327988742850721
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.959069675533101
  lightness: 0.8812595640774816
  saturation: 0.3113950127735734
  rhythmicContrast: 0.5339912632480264
purpose: []
