name: Sabira Collection
favicon: null
layout_spectrum: 0.64365
typography_spectrum: 0.77285
title: Sabira Collection
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4a333d'
    - '#fefefe'
    - '#b3a8ac'
    - '#d2cbcd'
    - '#806f75'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
