name: Sabira Collection
favicon: null
layout_spectrum: 0.19317705370485783
typography_spectrum: 0.77285
title: Sabira Collection
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c99945'
    - '#f3e3c9'
    - '#0a0b06'
    - '#653227'
    - '#c4394a'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
